appalanche:
  status:
    statuses:
      - code: "APPLIED"
        label: "Applied"
        maxRounds: 1
        colour: "#3498db"
        textColour: "#ffffff"

      - code: "ONLINE_ASSESSMENT"
        label: "Online Assessment"
        maxRounds: 1
        colour: "#fe7a2b"
        textColour: "#ffffff"

      - code: "PHONE_INTERVIEW_{0}"
        label: "Phone Interview"
        maxRounds: 10
        colour: "#f1c40f"
        textColour: "#222222"

      - code: "INTERVIEW_{0}"
        label: "Interview"
        maxRounds: 10
        colour: "#f1c40f"
        textColour: "#222222"

      - code: "TECHNICAL_INTERVIEW_{0}"
        label: "Technical Interview"
        maxRounds: 10
        colour: "#f1c40f"
        textColour: "#222222"

      - code: "OFFER_RECEIVED"
        label: "Offer Received"
        maxRounds: 1
        colour: "#2ecc71"
        textColour: "#ffffff"

      - code: "REJECTED"
        label: "Rejected"
        maxRounds: 1
        colour: "#000000"
        textColour: "#ffffff"

      - code: "WITHDREW"
        label: "Withdrew"
        maxRounds: 1
        colour: "#000000"
        textColour: "#ffffff"