spring.docker.compose.enabled=true
spring.docker.compose.file=compose.yaml,compose.override.yaml
management.endpoints.web.exposure.include=health,info,env,mappings,configprops
logging.level.com.jobhunt.backend.JobHunt_Modulith=INFO
logging.level.org.springframework.security=INFO