management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
spring.jpa.hibernate.ddl-auto=validate
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR
server.error.include-stacktrace=never
server.error.include-message=never