# Standard Environment Vars
spring.application.name=Appalanche-Modulith
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}
# Logo.dev Integration
integration.logo-dev.base-url=https://img.logo.dev
integration.logo-dev.token=${LOGO_DEV_TOKEN}
integration.logo-dev.connect-timeout=3000
integration.logo-dev.read-timeout=3000
integration.logo-dev.image.size=128
integration.logo-dev.image.format=jpg
# Timezone Related
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false
# Data Ingestion Sizes
server.tomcat.max-swallow-size=512KB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.max-file-size=5MB
# Configuration
spring.config.import=classpath:config/applications/status/status.yaml,classpath:config/applications/experience/experience.yaml